epochs: 3000
dt: 0.005  

optim_kwargs:
  learning_rate: 0.02
  clip_norm: .5
  weight_decay: .0

dataset_kwargs:
  batch_size : 256

optim_kwargs:
  learning_rate: 0.02
  clip_norm: .5
  weight_decay: .01

model_kwargs:
  burnin: 30
  norm: True
  ro_int: 20
  tau_s: 0.006
  tau_m: 0.02
  dropout_rate: .25
  neuron_model: "snnax.snn.AdaptiveLIF"
